name: fu

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    network_mode: "host"
    ports:
      - "3000:3000" # Your WebUI on 3000
    environment:
      - PORT=3000
      #- WEB_LOADER_ENGINE=playwright
      #- PLAYWRIGHT_WS_URL=ws://browserless:3000 # Internally they still use 3000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

  browserless:
    image: ghcr.io/browserless/chromium:latest
    container_name: browserless
    ports:
      - "4000:3000" # Maps your host's 4000 to the container's 3000
    restart: always
