# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."browserless" = {
    image = "ghcr.io/browserless/chromium:latest";
    ports = [
      "4000:3000/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=browserless"
      "--network=fu_default"
    ];
  };
  systemd.services."docker-browserless" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-fu_default.service"
    ];
    requires = [
      "docker-network-fu_default.service"
    ];
    partOf = [
      "docker-compose-fu-root.target"
    ];
    wantedBy = [
      "docker-compose-fu-root.target"
    ];
  };
  virtualisation.oci-containers.containers."open-webui" = {
    image = "ghcr.io/open-webui/open-webui:main";
    environment = {
      "PORT" = "3000";
    };
    ports = [
      "3000:3000/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--add-host=host.docker.internal:host-gateway"
      "--network=host"
    ];
  };
  systemd.services."docker-open-webui" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [
      "docker-compose-fu-root.target"
    ];
    wantedBy = [
      "docker-compose-fu-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-fu_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f fu_default";
    };
    script = ''
      docker network inspect fu_default || docker network create fu_default
    '';
    partOf = [ "docker-compose-fu-root.target" ];
    wantedBy = [ "docker-compose-fu-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-fu-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
