[General]
background=bg.png

[Theme]
Name=nier-automata
Description=NieR Automata SDDM Theme
Author=Max
Copyright=2024
License=GPL
Type=sddm-theme
Version=0.1
MainScript=Main.qml
ConfigFile=theme.conf
TranslationsDirectory=translations
Theme-Id=nier-automata
Theme-API=2.0
Greeter=sddm-greeter-qt6
